name: .NET build

on:
  push:
    branches: 
      - main
    paths-ignore:
      - docs/**
      - .github/workflows/docs.yml
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_MULTILEVEL_LOOKUP: false
  NUGET_XMLDOC_MODE: ''
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  restore:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    # Install the .NET workloads
    - uses: actions/setup-dotnet@v5
      id: cache
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: src/**/packages.lock.json

    - name: Run local/dotnet-restore@v1
      if: steps.cache.outputs.cache-hit != 'true'
      run: dotnet restore --locked-mode

  run-tests:
    runs-on: ubuntu-latest
    needs: restore

    steps:
    - uses: actions/checkout@v5
      with:
        lfs: true

    # Install .NET
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: |
          8.0.x
          9.0.x
        cache: true
        cache-dependency-path: src/**/packages.lock.json
    
    - name: Run local/dotnet-restore@v1
      run: dotnet restore --locked-mode

    # Test
    - name: Run local/dotnet-test@v1
      id: test
      run: >
        dotnet test
        --no-restore
        --
        --results-directory ${{ github.workspace }}/coverage/results
        --coverage
        --coverage-output-format cobertura
        
    - uses: actions/upload-artifact@v4
      if: failure() && steps.test.outcome == 'failure'
      with:
        name: TestResults
        path: |
          ${{ github.workspace }}/coverage/results/*.log
        retention-days: 1

    - uses: danielpalme/ReportGenerator-GitHub-Action@v5
      with:
        reports: ${{ github.workspace }}/coverage/results/*.cobertura.xml
        targetdir: '${{ github.workspace }}/coverage/reports'
        reporttypes: 'HtmlInline;Cobertura;MarkdownSummaryGithub'
        verbosity: 'Verbose'

    - name: Run local/set-test-summary@v1
      run: cat '${{ github.workspace }}/coverage/reports/SummaryGithub.md' >> $GITHUB_STEP_SUMMARY

    - uses: actions/upload-artifact@v4
      with:
        name: CoverageReports
        path: ${{ github.workspace }}/coverage/reports
        if-no-files-found: ignore

  create-nuget:
    runs-on: ubuntu-latest
    needs: restore
    
    env:
      Configuration: Release

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0 # get all history here, for semantic versioning

    # Install the .NET workload
    - uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x
        cache: true
        cache-dependency-path: src/**/packages.lock.json

    - name: Run local/dotnet-restore@v1
      run: dotnet restore --locked-mode

    - name: Run local/dotnet-build@v1
      run: dotnet build --no-restore

    - name: Run local/get-suffix@v1
      id: suffix
      run: |
        suffix=beta7
        if [ ${{ github.event_name }} == push ];
        then
          suffix=rc.1;
        fi

        echo "value=$suffix" >> $GITHUB_OUTPUT

    # Pack
    - name: Run local/dotnet-pack@v1
      run: dotnet pack --no-restore --output ${{ github.workspace }}/nupkg -property:ComputeSemanticVersion=true -property:SemanticVersionOutputPath=${{ github.workspace }}/versions -property:SemanticVersionIncrement=ReleaseLabel --version-suffix ${{ steps.suffix.outputs.value }}

    - uses: actions/upload-artifact@v4
      with:
        name: NuPkg
        if-no-files-found: error
        retention-days: 7
        path: ${{ github.workspace }}/nupkg

    - uses: actions/upload-artifact@v4
      with:
        name: Versions
        path: ${{ github.workspace }}/versions

  push:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      
      # enabled GitHub packages writing
      packages: write
      
      # enable GitHub OIDC token issuance for this job
      id-token: write
    needs: [ create-nuget, run-tests ]

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_MULTILEVEL_LOOKUP: false

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: NuPkg
        path: ${{ github.workspace }}/nupkg

    - name: Run local/dotnet-nuget-push-github@v1
      id: push-github
      working-directory: ${{ github.workspace }}/nupkg
      run: dotnet nuget push *.nupkg --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate

    - uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    
    - name: Run local/dotnet-nuget-push-nuget@v1
      id: push-nuget
      if: ${{ github.event_name == 'push' }}
      working-directory: ${{ github.workspace }}/nupkg
      run: dotnet nuget push *.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ steps.login.outputs.NUGET_API_KEY }} --skip-duplicate
      
    # delete-artifact
    - uses: GeekyEggo/delete-artifact@v5
      if: ${{ steps.push-github.conclusion == 'success' }}
      with:
        name: NuPkg
